# Generated by Django 3.2.5 on 2021-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_detail',
            name='crypto_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='crypto_detail',
            name='price_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
