# Generated by Django 3.2.5 on 2021-08-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_auto_20210830_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_date', models.DateField(blank=True, null=True)),
                ('crpto_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitcoin.crypto_detail')),
            ],
        ),
    ]
