# Generated by Django 3.2.5 on 2021-08-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0003_cryptorates'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_detail',
            name='crypto_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
